name: ✨ Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Please describe it in detail.

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A short, descriptive title
      placeholder: "Add support for Valkey"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What kind of feature is this?
      options:
        - New adapter/handler
        - Performance improvement
        - Developer experience
        - Documentation
        - Testing
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "I'd like to see..."
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show an example of how this would be used
      render: typescript
      placeholder: |
        const handler = createNewHandler({
          option: "value"
        });

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to open a PR for this feature
          required: false
