import { IMPLICIT_TAG_PREFIX } from "../types.js";

/**
 * Check if a tag is an implicit (system-generated) tag
 * Implicit tags are generated by Next.js with the _N_T_ prefix
 *
 * @param tag - The tag to check
 * @returns True if the tag is implicit, false otherwise
 */
export function isImplicitTag(tag: string): boolean {
  // Guard against non-string values that Next.js might pass
  if (typeof tag !== "string") {
    return false;
  }
  return tag.startsWith(IMPLICIT_TAG_PREFIX);
}
